export interface Todo {
  id: number;
  task: string;
  body?: string;
  board_id?: number;
  board_column_id?: number;
  position?: number;
  is_complete: boolean;
  user_id?: string;
  user?: string;
  created_at?: string;
  tags?: string[];
}



// id bigint generated by default as identity primary key,
//   user_id uuid references auth.users not null,
//   task text check (char_length(task) > 3),
//   board_id bigint references boards(id) not null,
//   board_column_id bigint references board_columns(id) not null,
//   position integer not null default 0,
//   is_complete boolean default false,
//   created_at timestamp with time zone default timezone('utc'::text, now()) not null